---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codeserver-cm
  namespace: codeserverns
data:
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: codeserver-146.190.19.90.nip.io
  TZ: Asia/Singapore

---
apiVersion: v1
kind: Secret
metadata:
  name: codeserver-secret
  namespace: codeserverns
type: Opaque
data:
  SUDO_PASSWORD: cGFzc3dvcmQ= #password
  PASSWORD: cGFzc3dvcmQ= #password
